#!/bin/bash

TEMPLATES="${TEMPLATES:-$HOME/bin/android-cli-dev/templates}"

gum log "Templates at: $TEMPLATES" || exit 0

APPNAME=$(gum input --placeholder "MyApp" --header "App Name")

APPNAME_SANE=$(echo "$APPNAME" | tr ' ' " | tr '-' ")


PKG_ID=$(gum input --placeholder "com.myapp.myapp" --header "Package Id")
if [[ ! "$PKG_ID" =~ ^[a-z][a-z0-9_]*(\.[a-z0-9_]+)+$ ]]; then
	gum style --foreground 1 "Invalid ID"
	exit 1
fi

gum style --foreground 2 "Project Sumary"
gum style --bold "Name:" "$APPNAME"
gum style --bold "Package ID:" "$PKG_ID"
gum confirm "Create Project?" || exit 0
PROJECT_DIR=~/projects/"$APPNAME_SANE"
gum style --foreground 2 "Project Location" "$PROJECT_DIR"

mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"
gum spin --spinner dot --title "Creating Project Structure ..." sleep 1

# BUILD.GRADLE
cat > build.gradle <<EOF
buildscript {
	repositories { google(); mavenCentral() }
	dependencies { classpath 'com.android.tools.build:gradle:8.2.0' }
}
allprojects { repositories { google(); mavenCentral() } }
EOF


# APP/BUILD.GRADLE
mkdir -p app/src/main
cat > app/build.gradle <<EOF
apply plugin: 'com.android.application'

android {
	namespace:'$PKG_ID'
	compileSdk 34
	defaultConfig {
		applicationId "$PKG_ID"
		minSdk 21
		targetSdk 34
		versionCode 1
		versionName "1.0"
	}
	buildTypes.release { minifyEnabled false }

}
dependencies {
	implementation 'androidx.appcompat:appcompat:1.6.1'
	implementation 'androidx.core:core-ktx:1.12.0'
}
EOF

# GENERATE MANIFEST

env APPNAME="$APPNAME" envsubst < $TEMPLATES/AndroidManifest.xml > app/src/main/AndroidManifest.xml 

# GENERATE MAinActivity.kt

mkdir -p app/src/main/java/$(echo $PKG_ID | tr '.' '/')

env PKG_ID="$PKG_ID" envsubst < $TEMPLATES/MainActivity.kt > app/src/main/java/$(echo $PKG_ID | tr '.' '/')/MainActivity.kt

